name: CI/CD FE Web Penus

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: fe web Penus
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/JHIC-SynchronizeTeams
            git pull origin main
            ~/.bun/bin/Bunx nuxi build
